services:
  # backend:
  #   container_name: backend
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend/app:/app/app
  #   environment:
  #     - APP_ENV=development
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - mongodb
  #   restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333  # API & Web UI
      - 6334:6334  # gRPC
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./storage/qdrant:/qdrant/storage
      - ./backend/config/qdrant/local.yaml:/qdrant/config/local.yaml  # Mount config file
      - ./backend/config/qdrant/development.yaml:/qdrant/config/development.yaml
      - ./backend/config/qdrant/production.yaml:/qdrant/config/production.yaml
    environment:
      - RUN_MODE=local
    restart: always


volumes:
  mongodb_data:
    driver: local
  qdrant_data:
    driver: local