services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app/app
      - ./storage/qdrant:/qdrant/storage  # align with qdrant storage mounted
    environment:
      - APP_ENV=development
      - REDIS_URL=redis://host.docker.internal:6379/0
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017
      - MONGO_DB_NAME=chat_db
      - QDRANT_URI=http://host.docker.internal:6333
      - QDRANT_COLLECTION_NAME=documents
      - LANGFUSE_URL=http://host.docker.internal:3000
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    restart: always
    networks:
      - default
      - langfuse-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./storage/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    restart: always
    networks:
      - default
      - langfuse-net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333  # API & Web UI
      - 6334:6334  # gRPC
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./storage/qdrant:/qdrant/storage  # mount persisted volume
      - ./backend/config/qdrant/local.yaml:/qdrant/config/local.yaml  # Mount config file
      - ./backend/config/qdrant/development.yaml:/qdrant/config/development.yaml
      - ./backend/config/qdrant/production.yaml:/qdrant/config/production.yaml
    environment:
      - RUN_MODE=local
    restart: always
    networks:
      - default
      - langfuse-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis:/data
    command: redis-server --appendonly yes
    networks:
      - default
      - langfuse-net

  celery_worker:
    container_name: celery_worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["poetry", "run", "celery", "-A", "app.services.celery.app", "worker", "--loglevel=info", "--concurrency=2"]
    # Override the ENTRYPOINT here, so it runs the celery worker instead
    entrypoint: ["/bin/sh", "-c", "poetry run celery -A app.services.celery.app worker --loglevel=info", "--concurrency=2"]
    depends_on:
      - redis
    volumes:
      - ./backend/app:/app/app
      - ./storage/qdrant:/qdrant/storage  # align with qdrant storage mounted
      - ~/:/host/home  # Mount the entire home directory on Unix-like systems
      # - /c/Users/YourUsername:/host/home  # Mount the user's home directory on Windows
    environment:
      - APP_ENV=development
      - HOST_HOME_DIR=/host/home
      - REDIS_URL=redis://host.docker.internal:6379/0
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017
      - MONGO_DB_NAME=chat_db
      - QDRANT_URI=http://host.docker.internal:6333
      - QDRANT_URI_HOST=http://host.docker.internal
      - QDRANT_URI_PORT=6333
      - QDRANT_COLLECTION_NAME=documents
      - LANGFUSE_URL=http://host.docker.internal:3000
    working_dir: /app
    networks:
      - default
      - langfuse-net


# volumes:
#   mongodb_data:
#     driver: local


networks:
  default:
  langfuse-net:
    external: true