services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app/app
      - ./storage/qdrant:/storage/qdrant
      - ~/:/host/home  # Mount the entire home directory on Unix-like systems
      # - /c/Users/YourUsername:/host/home  # Mount the user's home directory on Windows
    environment:
      - APP_ENV=development
      - HOST_HOME_DIR=/host/home
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017
      - MONGO_DB_NAME=chat_db
      - DOCUMENT_STORE_NAME=qdrant
      - QDRANT_URI=http://host.docker.internal:6333
      - QDRANT_DOCUMENT_STORE_STORAGE_DIR=/storage/qdrant
      - QDRANT_COLLECTION_NAME=documents
      - QDRANT_VECTOR_SIZE=384
      - LLM_PROVIDER=google
      # - OLLAMA_LLM_MODEL=mistral:7b    
      # - OLLAMA_LLM_BASE_URL=http://host.docker.internal:7869
      # - GOOGLE_API_KEY=
      # - HF_API_TOKEN=
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333  # API & Web UI
      - 6334:6334  # gRPC
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./storage/qdrant:/qdrant/storage  # mount persisted volume
      - ./backend/config/qdrant/local.yaml:/qdrant/config/local.yaml  # Mount config file
      - ./backend/config/qdrant/development.yaml:/qdrant/config/development.yaml
      - ./backend/config/qdrant/production.yaml:/qdrant/config/production.yaml
    environment:
      - RUN_MODE=local
    restart: always


volumes:
  mongodb_data:
    driver: local
  qdrant_data:
    driver: local