services:
  # backend:
  #   container_name: backend
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend/app:/app/app
  #   environment:
  #     - LOG_LEVEL=INFO
  #     - HF_API_TOKEN=***REMOVED***
  #     - MONGO_DB_NAME=chat_db
  #     - MONGO_URI=mongodb://admin:admin123@mongodb:27017
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - mongodb
  #   restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    restart: always

volumes:
  mongodb_data:
    driver: local